# dicionarios.py
# Mapeamento completo de nomes de países (inglês -> português)
country_translation = {
    "Afghanistan": "Afeganistão",
    "South Africa": "África do Sul",
    "Albania": "Albânia",
    "Germany": "Alemanha",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Antigua and Barbuda": "Antígua e Barbuda",
    "Saudi Arabia": "Arábia Saudita",
    "Algeria": "Argélia",
    "Argentina": "Argentina",
    "Armenia": "Armênia",
    "Australia": "Austrália",
    "Austria": "Áustria",
    "Azerbaijan": "Azerbaijão",
    "Bahamas": "Bahamas",
    "Bahrain": "Bahrein",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Belize": "Belize",
    "Benin": "Benim",
    "Belarus": "Bielorrússia",
    "Bolivia": "Bolívia",
    "Bosnia and Herzegovina": "Bósnia e Herzegovina",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "Brunei": "Brunei",
    "Bulgaria": "Bulgária",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Bhutan": "Butão",
    "Cape Verde": "Cabo Verde",
    "Cameroon": "Camarões",
    "Cambodia": "Camboja",
    "Canada": "Canadá",
    "Qatar": "Catar",
    "Kazakhstan": "Cazaquistão",
    "Chad": "Chade",
    "Chile": "Chile",
    "China": "China",
    "Cyprus": "Chipre",
    "Colombia": "Colômbia",
    "Comoros": "Comores",
    "Congo": "Congo",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croácia",
    "Cuba": "Cuba",
    "Curacao": "Curaçau",
    "Denmark": "Dinamarca",
    "Djibouti": "Djibuti",
    "Dominica": "Dominica",
    "Egypt": "Egito",
    "El Salvador": "El Salvador",
    "Ecuador": "Equador",
    "Eritrea": "Eritreia",
    "Slovakia": "Eslováquia",
    "Slovenia": "Eslovênia",
    "Spain": "Espanha",
    "United States": "Estados Unidos",
    "United States of America":"Estados Unidos",
    "Estonia": "Estônia",
    "Eswatini": "Eswatini",
    "Ethiopia": "Etiópia",
    "Fiji": "Fiji",
    "Philippines": "Filipinas",
    "Finland": "Finlândia",
    "France": "França",
    "Gabon": "Gabão",
    "Gambia": "Gâmbia",
    "Ghana": "Gana",
    "Greece": "Grécia",
    "Grenada": "Granada",
    "Guatemala": "Guatemala",
    "Guinea": "Guiné",
    "Guinea-Bissau": "Guiné-Bissau",
    "Guyana": "Guiana",
    "Haiti": "Haiti",
    "Honduras": "Honduras",
    "Hungary": "Hungria",
    "Yemen": "Iémen",
    "Marshall Islands": "Ilhas Marshall",
    "Solomon Islands": "Ilhas Salomão",
    "India": "Índia",
    "Indonesia": "Indonésia",
    "Iran": "Irã",
    "Iraq": "Iraque",
    "Ireland": "Irlanda",
    "Iceland": "Islândia",
    "Israel": "Israel",
    "Italy": "Itália",
    "Jamaica": "Jamaica",
    "Japan": "Japão",
    "Jordan": "Jordânia",
    "Kiribati": "Kiribati",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Laos": "Laos",
    "Lesotho": "Lesoto",
    "Latvia": "Letônia",
    "Lebanon": "Líbano",
    "Liberia": "Libéria",
    "Libya": "Líbia",
    "Liechtenstein": "Liechtenstein",
    "Lithuania": "Lituânia",
    "Luxembourg": "Luxemburgo",
    "North Macedonia": "Macedônia do Norte",
    "Madagascar": "Madagascar",
    "Malaysia": "Malásia",
    "Malawi": "Maláui",
    "Maldives": "Maldivas",
    "Mali": "Mali",
    "Malta": "Malta",
    "Morocco": "Marrocos",
    "Mauritius": "Maurício",
    "Mauritania": "Mauritânia",
    "Mexico": "México",
    "Micronesia": "Micronésia",
    "Mozambique": "Moçambique",
    "Moldova": "Moldávia",
    "Monaco": "Mônaco",
    "Mongolia": "Mongólia",
    "Montenegro": "Montenegro",
    "Namibia": "Namíbia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicaragua": "Nicarágua",
    "Niger": "Níger",
    "Nigeria": "Nigéria",
    "Norway": "Noruega",
    "New Zealand": "Nova Zelândia",
    "Oman": "Omã",
    "Netherlands": "Holanda",
    "Palau": "Palau",
    "Panama": "Panamá",
    "Papua New Guinea": "Papua-Nova Guiné",
    "Pakistan": "Paquistão",
    "Paraguay": "Paraguai",
    "Peru": "Peru",
    "Poland": "Polônia",
    "Portugal": "Portugal",
    "Kenya": "Quênia",
    "Central African Republic": "República Centro-Africana",
    "Czech Republic": "República Checa",
    "Republic of the Congo": "República do Congo",
    "Dominican Republic": "República Dominicana",
    "Rwanda": "Ruanda",
    "Romania": "Romênia",
    "Russia Population": "Rússia",
    "San Marino": "São Marino",
    "Saint Kitts and Nevis": "São Cristóvão e Nevis",
    "São Tomé and Príncipe": "São Tomé e Príncipe",
    "Senegal": "Senegal",
    "Sierra Leone": "Serra Leoa",
    "Syria": "Síria",
    "Singapore": "Singapura",
    "Somalia": "Somália",
    "Sri Lanka": "Sri Lanka",
    "Swaziland": "Suazilândia",
    "Sudan": "Sudão",
    "South Sudan": "Sudão do Sul",
    "Suriname": "Suriname",
    "Sweden": "Suécia",
    "Switzerland": "Suíça",
    "Tanzania": "Tanzânia",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad and Tobago": "Trinidad e Tobago",
    "Tunisia": "Tunísia",
    "Turkmenistan": "Turcomenistão",
    "Turkey": "Turquia",
    "Tuvalu": "Tuvalu",
    "Uganda": "Uganda",
    "Ukraine": "Ucrânia",
    "Uruguay": "Uruguai",
    "Vanuatu": "Vanuatu",
    "Vatican City": "Vaticano",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnã",
    "Zambia": "Zâmbia",
    "Zimbabwe": "Zimbábue"
}

# Mapeamento completo de códigos de países (ISO 3166-1 alpha-2)
country_code_to_name = {
    "AF": "Afghanistan",
    "ZA": "South Africa",
    "AL": "Albania",
    "DE": "Germany",
    "AD": "Andorra",
    "AO": "Angola",
    "AG": "Antigua and Barbuda",
    "SA": "Saudi Arabia",
    "DZ": "Algeria",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BZ": "Belize",
    "BJ": "Benin",
    "BY": "Belarus",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BR": "Brazil",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "BT": "Bhutan",
    "CV": "Cape Verde",
    "CM": "Cameroon",
    "KH": "Cambodia",
    "CA": "Canada",
    "QA": "Qatar",
    "KZ": "Kazakhstan",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CY": "Cyprus",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "Curacao",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "EG": "Egypt",
    "SV": "El Salvador",
    "EC": "Ecuador",
    "ER": "Eritrea",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ES": "Spain",
    "US": "United States",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "PH": "Philippines",
    "FI": "Finland",
    "FR": "France",
    "GA": "Gabon",
    "GM": "Gambia",
    "GH": "Ghana",
    "GR": "Greece",
    "GD": "Grenada",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungary",
    "YE": "Yemen",
    "MH": "Marshall Islands",
    "SB": "Solomon Islands",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IS": "Iceland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JO": "Jordan",
    "KI": "Kiribati",
    "XK": "Kosovo",
    "KW": "Kuwait",
    "LA": "Laos",
    "LS": "Lesotho",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MK": "North Macedonia",
    "MG": "Madagascar",
    "MY": "Malaysia",
    "MW": "Malawi",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MA": "Morocco",
    "MU": "Mauritius",
    "MR": "Mauritania",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MZ": "Mozambique",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NO": "Norway",
    "NZ": "New Zealand",
    "OM": "Oman",
    "NL": "Netherlands",
    "PW": "Palau",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PK": "Pakistan",
    "PY": "Paraguay",
    "PE": "Peru",
    "PL": "Poland",
    "PT": "Portugal",
    "KE": "Kenya",
    "CF": "Central African Republic",
    "CZ": "Czech Republic",
    "CD": "Republic of the Congo",
    "DO": "Dominican Republic",
    "RW": "Rwanda",
    "RO": "Romania",
    "RU": "Russia Population",
    "SM": "San Marino",
    "KN": "Saint Kitts and Nevis",
    "ST": "São Tomé and Príncipe",
    "SN": "Senegal",
    "SL": "Sierra Leone",
    "SY": "Syria",
    "SG": "Singapore",
    "SO": "Somalia",
    "LK": "Sri Lanka",
    "SS": "South Sudan",
    "SD": "Sudan",
    "SR": "Suriname",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TZ": "Tanzania",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TM": "Turkmenistan",
    "TR": "Turkey",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "UY": "Uruguai",
    "VU": "Vanuatu",
    "VA": "Vatican City",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}
